// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace location2
{
	public partial class test : UIViewController
	{
		public test (IntPtr handle) : base (handle)
		{
		}
	}
}
