#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("goheja.Resource", IsApplication=true)]

namespace goheja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::goheja.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::goheja.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::goheja.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::goheja.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::goheja.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::goheja.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::goheja.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::goheja.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::goheja.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::goheja.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::goheja.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::goheja.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::goheja.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::goheja.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::goheja.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::goheja.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::goheja.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::goheja.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::goheja.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::goheja.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::goheja.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::goheja.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::goheja.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::goheja.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::goheja.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::goheja.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::goheja.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::goheja.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::goheja.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::goheja.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::goheja.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::goheja.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::goheja.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::goheja.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::goheja.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::goheja.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::goheja.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int active_tab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int athletes_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bikeRound_new = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int border_bottom = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int border_vertical = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int calender_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int calender_icon_active_new = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int calender_icon_inactive_new = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cell_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dist_new = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edit_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int email_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int go_button = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int goheja_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int header = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int header_bg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int heart_new = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int heja_icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int home_icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int horizontal_line = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_errorstatus = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_successstatus = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon_01 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_02 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon_03 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int icon_04 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int icon_05 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int icon_06 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon_07 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int icon_back = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int img_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int key_icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int line_new = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int menu_icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int menu_icon_01 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int mont_new = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ninja = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int pop_up_bg = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int resume_active = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int resume_inactive = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int roundedbg = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int roundedbgdark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int runRound_new = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int speed_new = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int splash = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int stop_active = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int switch_off = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int text_icon = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int timer_new = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int transparent = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int user_active_new = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int user_icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int user_inactive_new = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int watch_icon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int watch_new = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int watch_new2 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int watt_new = 2130837565;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06005a
			public const int AAAA = 2131099738;
			
			// aapt resource value: 0x7f060000
			public const int ActionBar = 2131099648;
			
			// aapt resource value: 0x7f0600af
			public const int ActionBarLeft = 2131099823;
			
			// aapt resource value: 0x7f0600ae
			public const int ActionBarMain = 2131099822;
			
			// aapt resource value: 0x7f0600b1
			public const int ActionBarRight = 2131099825;
			
			// aapt resource value: 0x7f06002f
			public const int ImageView1 = 2131099695;
			
			// aapt resource value: 0x7f060005
			public const int LinearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int LinearLayout2 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int LinearLayout3 = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int StartPractice = 2131099675;
			
			// aapt resource value: 0x7f0600b2
			public const int Tab1Icon = 2131099826;
			
			// aapt resource value: 0x7f0600b5
			public const int Tab2Icon = 2131099829;
			
			// aapt resource value: 0x7f0600b8
			public const int Tab3Icon = 2131099832;
			
			// aapt resource value: 0x7f0600b4
			public const int TabStrip1 = 2131099828;
			
			// aapt resource value: 0x7f0600b7
			public const int TabStrip2 = 2131099831;
			
			// aapt resource value: 0x7f0600b9
			public const int TabStrip3 = 2131099833;
			
			// aapt resource value: 0x7f060001
			public const int TitleBarText = 2131099649;
			
			// aapt resource value: 0x7f0600b0
			public const int TitleBarTextMain = 2131099824;
			
			// aapt resource value: 0x7f0600a7
			public const int age = 2131099815;
			
			// aapt resource value: 0x7f060057
			public const int bestresults = 2131099735;
			
			// aapt resource value: 0x7f06001f
			public const int btnBack = 2131099679;
			
			// aapt resource value: 0x7f0600ad
			public const int btnGo = 2131099821;
			
			// aapt resource value: 0x7f06001e
			public const int btnLD = 2131099678;
			
			// aapt resource value: 0x7f060034
			public const int btnSave = 2131099700;
			
			// aapt resource value: 0x7f0600ac
			public const int btnTermsAccepted = 2131099820;
			
			// aapt resource value: 0x7f060013
			public const int btnTotalTime = 2131099667;
			
			// aapt resource value: 0x7f0600a0
			public const int btnUpdate = 2131099808;
			
			// aapt resource value: 0x7f060059
			public const int collapseBestResults = 2131099737;
			
			// aapt resource value: 0x7f060050
			public const int collapseGoals = 2131099728;
			
			// aapt resource value: 0x7f060048
			public const int collapsePhysical = 2131099720;
			
			// aapt resource value: 0x7f060066
			public const int collapseSelfRanking = 2131099750;
			
			// aapt resource value: 0x7f060019
			public const int content = 2131099673;
			
			// aapt resource value: 0x7f060003
			public const int drawerHandle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int drawerHandleLayout = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int dummyType = 2131099677;
			
			// aapt resource value: 0x7f06005b
			public const int edtBestResults = 2131099739;
			
			// aapt resource value: 0x7f060093
			public const int edtBike = 2131099795;
			
			// aapt resource value: 0x7f060052
			public const int edtGoals = 2131099730;
			
			// aapt resource value: 0x7f060049
			public const int edtPhysical = 2131099721;
			
			// aapt resource value: 0x7f060080
			public const int edtRun = 2131099776;
			
			// aapt resource value: 0x7f060067
			public const int edtSeflRanking = 2131099751;
			
			// aapt resource value: 0x7f06006f
			public const int edtSwim = 2131099759;
			
			// aapt resource value: 0x7f060030
			public const int etFirstName = 2131099696;
			
			// aapt resource value: 0x7f060032
			public const int etMail = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int etPhone = 2131099699;
			
			// aapt resource value: 0x7f0600aa
			public const int etPsw = 2131099818;
			
			// aapt resource value: 0x7f0600a8
			public const int etUserName = 2131099816;
			
			// aapt resource value: 0x7f060031
			public const int etlastName = 2131099697;
			
			// aapt resource value: 0x7f060038
			public const int goals = 2131099704;
			
			// aapt resource value: 0x7f060022
			public const int icon01 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int icon02 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int icon03 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int icon04 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int icon05 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int icon06 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int icon07 = 2131099688;
			
			// aapt resource value: 0x7f06000a
			public const int imageView1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imageView100 = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int imageView103 = 2131099666;
			
			// aapt resource value: 0x7f06006e
			public const int imgSwim = 2131099758;
			
			// aapt resource value: 0x7f06002b
			public const int ivTest = 2131099691;
			
			// aapt resource value: 0x7f06003e
			public const int lblAddress = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int lblAge = 2131099712;
			
			// aapt resource value: 0x7f06003f
			public const int lblBib = 2131099711;
			
			// aapt resource value: 0x7f060042
			public const int lblBirth = 2131099714;
			
			// aapt resource value: 0x7f06003d
			public const int lblCountry = 2131099709;
			
			// aapt resource value: 0x7f060043
			public const int lblEmail = 2131099715;
			
			// aapt resource value: 0x7f06003b
			public const int lblFirstname = 2131099707;
			
			// aapt resource value: 0x7f060041
			public const int lblGender = 2131099713;
			
			// aapt resource value: 0x7f06003c
			public const int lblLastname = 2131099708;
			
			// aapt resource value: 0x7f060044
			public const int lblPhone = 2131099716;
			
			// aapt resource value: 0x7f06002e
			public const int lblUsername = 2131099694;
			
			// aapt resource value: 0x7f060029
			public const int linearLayout1 = 2131099689;
			
			// aapt resource value: 0x7f060072
			public const int linearLayout10 = 2131099762;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout100 = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout101 = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout102 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout104 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout105 = 2131099671;
			
			// aapt resource value: 0x7f060073
			public const int linearLayout12 = 2131099763;
			
			// aapt resource value: 0x7f060047
			public const int linearLayout13 = 2131099719;
			
			// aapt resource value: 0x7f06004f
			public const int linearLayout14 = 2131099727;
			
			// aapt resource value: 0x7f060058
			public const int linearLayout15 = 2131099736;
			
			// aapt resource value: 0x7f060065
			public const int linearLayout16 = 2131099749;
			
			// aapt resource value: 0x7f06002a
			public const int linearLayout2 = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int linearLayout3 = 2131099693;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout4 = 2131099652;
			
			// aapt resource value: 0x7f060069
			public const int linearLayout5 = 2131099753;
			
			// aapt resource value: 0x7f06006d
			public const int linearLayout6 = 2131099757;
			
			// aapt resource value: 0x7f060070
			public const int linearLayout8 = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int linearLayout9 = 2131099761;
			
			// aapt resource value: 0x7f0600a3
			public const int loadingImage = 2131099811;
			
			// aapt resource value: 0x7f0600a1
			public const int loadingProgressBar = 2131099809;
			
			// aapt resource value: 0x7f0600a4
			public const int loadingProgressWheel = 2131099812;
			
			// aapt resource value: 0x7f0600a9
			public const int note = 2131099817;
			
			// aapt resource value: 0x7f0600ba
			public const int pager = 2131099834;
			
			// aapt resource value: 0x7f06002c
			public const int perImage = 2131099692;
			
			// aapt resource value: 0x7f060046
			public const int physical = 2131099718;
			
			// aapt resource value: 0x7f060039
			public const int profile = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int relativeLayout1 = 2131099706;
			
			// aapt resource value: 0x7f060045
			public const int relativeLayout2 = 2131099717;
			
			// aapt resource value: 0x7f060036
			public const int resetCalBtn = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int scrollView1 = 2131099703;
			
			// aapt resource value: 0x7f060064
			public const int selfrankings = 2131099748;
			
			// aapt resource value: 0x7f060035
			public const int seriousBtn = 2131099701;
			
			// aapt resource value: 0x7f060006
			public const int speedFL = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int speedTv = 2131099657;
			
			// aapt resource value: 0x7f06001c
			public const int stopPractice = 2131099676;
			
			// aapt resource value: 0x7f0600ab
			public const int termsBtn = 2131099819;
			
			// aapt resource value: 0x7f06000e
			public const int textView1 = 2131099662;
			
			// aapt resource value: 0x7f0600a2
			public const int textViewStatus = 2131099810;
			
			// aapt resource value: 0x7f060051
			public const int textview111 = 2131099729;
			
			// aapt resource value: 0x7f0600a6
			public const int toolBar = 2131099814;
			
			// aapt resource value: 0x7f060018
			public const int tvAltitude = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int tvBpm = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int tvDistance = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int tvSpeed = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int tvWatt = 2131099670;
			
			// aapt resource value: 0x7f060061
			public const int txt10KRun = 2131099745;
			
			// aapt resource value: 0x7f06009e
			public const int txtBFTPHB = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int txtBFTPower = 2131099807;
			
			// aapt resource value: 0x7f06004d
			public const int txtBMI = 2131099725;
			
			// aapt resource value: 0x7f060094
			public const int txtBZone1HR = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int txtBZone1POWER = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int txtBZone2HR = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int txtBZone2POWER = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int txtBZone3HR = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int txtBZone3POWER = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int txtBZone4HR = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int txtBZone4POWER = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int txtBZone5HR = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int txtBZone5POWER = 2131099805;
			
			// aapt resource value: 0x7f060056
			public const int txtCountry = 2131099734;
			
			// aapt resource value: 0x7f060060
			public const int txtDistance = 2131099744;
			
			// aapt resource value: 0x7f06004e
			public const int txtFatPercentage = 2131099726;
			
			// aapt resource value: 0x7f06005f
			public const int txtHDistance = 2131099743;
			
			// aapt resource value: 0x7f060062
			public const int txtHMarathon = 2131099746;
			
			// aapt resource value: 0x7f06004c
			public const int txtHeight = 2131099724;
			
			// aapt resource value: 0x7f060054
			public const int txtID = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int txtLastname = 2131099733;
			
			// aapt resource value: 0x7f060063
			public const int txtMarathon = 2131099747;
			
			// aapt resource value: 0x7f06005e
			public const int txtOlympic = 2131099742;
			
			// aapt resource value: 0x7f060091
			public const int txtRFTPHB = 2131099793;
			
			// aapt resource value: 0x7f060090
			public const int txtRFTPace = 2131099792;
			
			// aapt resource value: 0x7f060092
			public const int txtRFTPower = 2131099794;
			
			// aapt resource value: 0x7f060081
			public const int txtRZone1HR = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int txtRZone1PACE = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int txtRZone1Power = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int txtRZone2HR = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int txtRZone2PACE = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int txtRZone2Power = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int txtRZone3HR = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int txtRZone3PACE = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int txtRZone3Power = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int txtRZone4HR = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int txtRZone4PACE = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int txtRZone4Power = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int txtRZone5HR = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int txtRZone5PACE = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int txtRZone5Power = 2131099791;
			
			// aapt resource value: 0x7f06006c
			public const int txtRankBike = 2131099756;
			
			// aapt resource value: 0x7f06006b
			public const int txtRankRun = 2131099755;
			
			// aapt resource value: 0x7f06006a
			public const int txtRankSwim = 2131099754;
			
			// aapt resource value: 0x7f06007f
			public const int txtSFTPHB = 2131099775;
			
			// aapt resource value: 0x7f06007e
			public const int txtSFTPace = 2131099774;
			
			// aapt resource value: 0x7f060074
			public const int txtSZone1HR = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int txtSZone1PACE = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int txtSZone2HR = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int txtSZone2PACE = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int txtSZone3HR = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int txtSZone3PACE = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int txtSZone4HR = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int txtSZone4PACE = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int txtSZone5HR = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int txtSZone5PACE = 2131099773;
			
			// aapt resource value: 0x7f06005d
			public const int txtSprint = 2131099741;
			
			// aapt resource value: 0x7f06004b
			public const int txtWeight = 2131099723;
			
			// aapt resource value: 0x7f0600b3
			public const int vertical1 = 2131099827;
			
			// aapt resource value: 0x7f0600b6
			public const int vertical2 = 2131099830;
			
			// aapt resource value: 0x7f06005c
			public const int viewBestResults = 2131099740;
			
			// aapt resource value: 0x7f060053
			public const int viewGoals = 2131099731;
			
			// aapt resource value: 0x7f06004a
			public const int viewPhysical = 2131099722;
			
			// aapt resource value: 0x7f060068
			public const int viewSelfRankings = 2131099752;
			
			// aapt resource value: 0x7f060020
			public const int webViewCalen = 2131099680;
			
			// aapt resource value: 0x7f0600a5
			public const int webViewProfile = 2131099813;
			
			// aapt resource value: 0x7f060021
			public const int whatItLabel = 2131099681;
			
			// aapt resource value: 0x7f06001a
			public const int wvCurrentEvent = 2131099674;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnalyticsActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fCalendar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fEvents = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fProfile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fSerious = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loading = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingimage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingprogress = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfileWebViewActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RegisterActivity = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SwipeTabActivity = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int BlackEditBox = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int EditBoxIcon = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int MyTheme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
