using System;
namespace PortableLibrary
{
	public static class License
	{
		public const string Key =
			"ABIBEgISB3pOAGkAdAByAG8Ae1gcSTfcvPjmZl46L8CbiXZ7tSxjIfKiFyOSKfdW" +
			"i/zihmC/qdtgHHY8fNQwbSykfMjm7E3yS4FJpziWOnLwZzPHjX/nL9vHH+pxGGBb" +
			"fyhWwA9qv2qf7hXU8rsjm8pnqonffyibxsTsMbi+VZ+PlvuLtHm9NGua7RQxnUuh" +
			"Vb8Es+fkacLfI8fFCPPny2ZkoB+VQcQHjWg3712A+uED9dEP5jiWW4qQEo9jOq51" +
			"dAbUTsXCQBv9ibz6R1nMIQHtuAALr33Yuih4EA57MhGpBBCZLqLx1xC8HsjXPERN" +
			"Tu99ma6/UrbHpTQHG1Hj+EaBraMyJl5iCkfmYXlABv+SzQ2rmRjZqGYUDWuHojTX" +
			"mDBzj/ipkYMQYPNt/fWB1c7mi4/82Z6uHiIBrg/DR+aeow1UHsMJMT/v4kYk5eim" +
			"DO1wU0OTw4KFsnOVT0QMQ6LapRVxRdI4vae+w7LCM4QCnyhOdtnDFRjXxBl0rgrj" +
			"oGh+aP7ovgP0jBprr9+w7S75nJv1CzDHSuuE8dU3HmJ6DuvP/rXBpfD5CoWE/13w" +
			"5hRJyVvdhI2f/X35UZbgK9WsAZgl3EHSpE5JExUYSaXiYjzX0/Jy7W9fgmC7h79m" +
			"W+XZLSOOWAhFUlVMcBVHM9zeukykPnpwVI7XthWJIxbAMKdirmNqnqjn/QRc2G/o" +
			"JNAwggVkMIIETKADAgECAhAiELIXSwsSf7soBS4RsyUKMA0GCSqGSIb3DQEBBQUA" +
			"MIG0MQswCQYDVQQGEwJVUzEXMBUGA1UEChMOVmVyaVNpZ24sIEluYy4xHzAdBgNV" +
			"BAsTFlZlcmlTaWduIFRydXN0IE5ldHdvcmsxOzA5BgNVBAsTMlRlcm1zIG9mIHVz" +
			"ZSBhdCBodHRwczovL3d3dy52ZXJpc2lnbi5jb20vcnBhIChjKTEwMS4wLAYDVQQD" +
			"EyVWZXJpU2lnbiBDbGFzcyAzIENvZGUgU2lnbmluZyAyMDEwIENBMB4XDTEzMDky" +
			"NDAwMDAwMFoXDTE2MTAyMzIzNTk1OVowgacxCzAJBgNVBAYTAlVTMRUwEwYDVQQI" +
			"EwxQZW5uc3lsdmFuaWExEzARBgNVBAcTClBpdHRzYnVyZ2gxFTATBgNVBAoUDENv" +
			"bXBvbmVudE9uZTE+MDwGA1UECxM1RGlnaXRhbCBJRCBDbGFzcyAzIC0gTWljcm9z" +
			"b2Z0IFNvZnR3YXJlIFZhbGlkYXRpb24gdjIxFTATBgNVBAMUDENvbXBvbmVudE9u" +
			"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALnLoJqpSVVqnJLza05l" +
			"TIcakcvyl7dxBxZ+cwk4Cqk6+UaC6f5Z5LvRD1+AhiARulIgI7vPgkCf+c83iOVi" +
			"QWyJuXFJMnGava3AZ6X/o0DaUqzYzFOWz/MrAzOJvYMtrj/NT9m8BWei+UkY1NWU" +
			"ytiSa0JINYt55i/FztxXtP7K27Lj3ZYwwUkNLOKJ4f+qkR0QSnygYUQQyMDOLg5v" +
			"fYkDLdUQkNretBT2JZ6x6dkNcCpif5dbZ01MOFEEjZJlGdnvrenuOYfw5CNloDSC" +
			"RzttSJ89JtJOjQxyrBQf1ylOXoiXCPpzAXCU2SF/dYXSimVM8pT0NZ7pUNG1H+Az" +
			"2nMCAwEAAaOCAXswggF3MAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgeAMEAGA1Ud" +
			"HwQ5MDcwNaAzoDGGL2h0dHA6Ly9jc2MzLTIwMTAtY3JsLnZlcmlzaWduLmNvbS9D" +
			"U0MzLTIwMTAuY3JsMEQGA1UdIAQ9MDswOQYLYIZIAYb4RQEHFwMwKjAoBggrBgEF" +
			"BQcCARYcaHR0cHM6Ly93d3cudmVyaXNpZ24uY29tL3JwYTATBgNVHSUEDDAKBggr" +
			"BgEFBQcDAzBxBggrBgEFBQcBAQRlMGMwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3Nw" +
			"LnZlcmlzaWduLmNvbTA7BggrBgEFBQcwAoYvaHR0cDovL2NzYzMtMjAxMC1haWEu" +
			"dmVyaXNpZ24uY29tL0NTQzMtMjAxMC5jZXIwHwYDVR0jBBgwFoAUz5mp6nsm9EvJ" +
			"jo/X8AUm7+PSp50wEQYJYIZIAYb4QgEBBAQDAgQQMBYGCisGAQQBgjcCARsECDAG" +
			"AQEAAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQBhzVY5zjwYAFjmIa2JSWbqeXQ1jrf2" +
			"o5DoRYWgI/+4LEpJ+U2o+VAI5kIYSNGp5Yjq7XvQosjs/C6qdwpfTd3bh2lEER4X" +
			"CRzpo+4HK9Wxwj0D8P1UoUn43LjlbMB/GzRRhNq0BN+ETlD0+BejspoUssd5GRhG" +
			"LNOXmtDV+9/a7j7h9t5JEMk++JblysVe6UpcgtoY9XguZLsm5DOhQT0QIlgOIK1Q" +
			"Sl/whiKGdPBfD5jN4/SHsGVUbPpC+Pxjh5yT/LSm9+Nqk+tzMQQcpbTfeLKs9kLg" +
			"sG4Uo9fsg5wOl4FN4CBHo2CLXEqtriy3//rpUMOutVKmm1awHhgGqsuFMIICuDCC" +
			"AaCgAwIBAgIITD3T4nCaFOgwDQYJKoZIhvcNAQEFBQAwHDEaMBgGA1UEAwwRR0Mt" +
			"WFUxMTcwMC0zNTg0NDMwHhcNMTcwMTAxMDAwMDAwWhcNMTgwNDMwMDAwMDAwWjAc" +
			"MRowGAYDVQQDDBFHQy1YVTExNzAwLTM1ODQ0MzCCASIwDQYJKoZIhvcNAQEBBQAD" +
			"ggEPADCCAQoCggEBAJ7+txa/czeug1ZLqmHtRcdvu632yAuxA/7XYdHnhcHwiOB3" +
			"197+vF45XkvYnyLiwx4IHG1tgDVZjlhY6ZhMubV6a+GQq/VMLsYwhnWfPCa7V4Vv" +
			"+zVndmyyxh2GVSW4kkBiVSWnDWQCOSEdzMfZoIWAABhUVpmHiiCotLuV7q6/CYAA" +
			"G6RS/i092nELRmVg78zUNa9ZscG3/2lmQALB8RYxcyDkvToBZCOoXXC2fCS+X0Ir" +
			"MHJ/gnCPAylC2V9LpA63/SDtv/ON3HEgMDGx4STSgOXR0iRdjinH9JRMjT8bb2no" +
			"e4ECGij/o94g+p9XGpEiuTOcaeANnLSI80riHx0CAwEAATANBgkqhkiG9w0BAQUF" +
			"AAOCAQEAkaLZiY9aR/l5y5EcZIZmuTAJb3hs3n1vKIqFX6f6ivkao+NPQJXcLbyW" +
			"zUxK6iC3ExR+cQsV57vajMpV37DLuPhhR3Ke+nEoYkdAriiDriVcReXZDJKeAh+r" +
			"PMTiwzErm7xCtwu1HPGK5fDzUn6tdMOiG4GswTuQvm9Lp0QMJMSh5EXf+dcMChrc" +
			"nRbR+E3PFFjH8w8zehFxOZKLedbBD5ztYDkR5J8W8pFAZXx6069zim6X2Jko46zo" +
			"mnSW721iUyjZ4ijriS8b3T0Xv3QJnPL5V4k1vCI8VvFayG/C9a4z4UAhDyIyJR/T" +
			"sNUQXVmM2YffNm56A4edgyHXvDC0fQ==";
	}

}
